version: '3.7'

services:

  caddy:
    build:
      context: ./caddy 
      dockerfile: caddy_dockerfile
    container_name: caddy
    restart: unless-stopped
    networks:
      - home_net
    ports:
      - "3000:3000"
  
  ubuntu_server:
    build:
      context: ./server
      dockerfile: ubuntu_server_dockerfile
    container_name: ubuntu_server
    restart: unless-stopped
    networks:
      - home_net
    volumes:
      - ./server/app:/opt/app
    environment:
      - PYTHONUNBUFFERED=1


networks:
  home_net:
    external:
      name: home_net
